[project]
name = "social-media-manager-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"    
authors = [
    { name = "frrmrc", email = "marco2004.ferrarini@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.198.0",
    "google-auth-oauthlib>=1.4.0",
    "grandalf>=0.8",
    "langchain-core>=1.5.3",
    "langchain-openai>=1.4.1",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.10",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "tenacity>=9.1.4",
    "tzlocal>=5.4.4",
]

[project.scripts]
social-media-manager-agent = "social_media_manager_agent.cli:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
